blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/nicolasbaud/crm/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Support question
    url: https://github.com/nicolasbaud/crm/discussions/new?category=q-a
    about: Ask the community for help
  - name: Discord
    url: https://discord.gg/tTxppCUxn4
    about: For quick help, ask questions in the appropriate channel
